# Generated by Django 4.2.5 on 2023-11-28 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('idCiudad', models.AutoField(db_column='idCiudad', default=1, primary_key=True, serialize=False)),
                ('Ciudad', models.CharField(db_column='Ciudad', default='Ciudad', max_length=50)),
            ],
            options={
                'db_table': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('idFavorito', models.AutoField(db_column='idFavorito', primary_key=True, serialize=False)),
                ('fk_Ciudad', models.ForeignKey(db_column='fk_Ciudad', on_delete=django.db.models.deletion.CASCADE, to='api.ciudades')),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('idConsulta', models.AutoField(db_column='idConsulta', default=1, primary_key=True, serialize=False)),
                ('Temperatura', models.FloatField(db_column='Temperatura', default=0.1)),
                ('velViento', models.CharField(db_column='velViento', default='0 Km/h', max_length=10)),
                ('Latitud', models.CharField(db_column='Latitud', default='0 N', max_length=10)),
                ('Longitud', models.CharField(db_column='Longitud', default='0 W', max_length=10)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=45)),
                ('fk_Ciudad', models.ForeignKey(db_column='fk_Ciudad', on_delete=django.db.models.deletion.CASCADE, to='api.ciudades')),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Consultas',
            },
        ),
    ]
